# Generated by Django 6.0.2 on 2026-03-11 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillforgeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '088888888...'. Up to 15 digits allowed.", regex='^\\d{8,15}$')]),
        ),
    ]
