# Generated by Django 6.0 on 2026-03-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skillforgeuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillforgeuser',
            name='bio',
        ),
    ]
