# Generated by Django 6.0 on 2026-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_skillforgeuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillforgeuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', upload_to='profile_images/'),
        ),
    ]
