# Generated by Django 6.0 on 2026-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_skillforgeuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillforgeuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
