# Generated by Django 6.0 on 2026-03-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_skillforgeuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillforgeuser',
            name='phone_number',
        ),
    ]
