# Generated by Django 6.0 on 2026-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_skillforgeuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillforgeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
