# Generated by Django 6.0 on 2026-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_create_default_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillforgeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
