# Generated by Django 6.0 on 2026-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('goal', models.CharField(max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('skils', models.ManyToManyField(related_name='learning_paths', to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
