# Generated by Django 6.0.2 on 2026-03-11 18:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0011_alter_skill_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True, validators=[core.validators.blank_validator])),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.TextField(validators=[core.validators.blank_validator])),
                ('skills', models.ManyToManyField(related_name='learning_paths', to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
