# Generated by Django 6.0 on 2026-01-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='goal',
            field=models.TextField(),
        ),
    ]
