# Generated by Django 6.0 on 2026-03-28 13:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_learningpath_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='title',
            field=models.CharField(max_length=255, validators=[core.validators.blank_validator]),
        ),
    ]
