# Generated by Django 6.0 on 2026-02-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_alter_learningpath_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningpath',
            old_name='goal',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='learningpath',
            old_name='skils',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='is_public',
        ),
    ]
