# Generated by Django 6.0 on 2026-02-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0003_rename_goal_learningpath_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
