# Generated by Django 6.0 on 2026-02-05 17:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0004_alter_learningpath_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[core.validators.blank_validator]),
        ),
    ]
