# Generated by Django 6.0 on 2026-02-06 15:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0005_alter_learningpath_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='description',
            field=models.TextField(validators=[core.validators.blank_validator]),
        ),
    ]
