# Generated by Django 6.0 on 2026-02-09 17:20

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0006_alter_learningpath_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill', related_name='learning_paths'),
        ),
    ]
