# Generated by Django 6.0 on 2026-02-01 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_category_name_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='estimated_hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'The estimated hours must be 1 or more')]),
        ),
    ]
