# Generated by Django 6.0 on 2026-02-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('skills', '0006_alter_skill_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
