# Generated by Django 6.0 on 2026-02-05 17:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_skill_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[core.validators.blank_validator]),
        ),
    ]
