# Generated by Django 6.0 on 2026-02-06 15:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(validators=[core.validators.blank_validator]),
        ),
    ]
