# Generated by Django 6.0 on 2026-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_alter_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
