# Generated by Django 6.0 on 2026-03-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_alter_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_published',
        ),
    ]
