# Generated by Django 6.0 on 2026-03-28 13:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_remove_skill_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, validators=[core.validators.blank_validator]),
        ),
    ]
