# Generated by Django 6.0 on 2026-05-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_alter_skill_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
