# Generated by Django 6.0 on 2026-01-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0003_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Book', 'Book')], max_length=100)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
