# Generated by Django 6.0 on 2026-01-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('skills', '0003_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='skills',
        ),
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=models.ManyToManyField(related_name='resources', to='skills.skill'),
        ),
    ]
