# Generated by Django 6.0 on 2026-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_skills_resource_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Book', 'Book'), ('Other', 'Other')], max_length=100),
        ),
    ]
