# Generated by Django 6.0 on 2026-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
