# Generated by Django 6.0 on 2026-02-05 17:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resource_slug_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[core.validators.blank_validator]),
        ),
    ]
