# Generated by Django 6.0 on 2026-03-28 13:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=100, validators=[core.validators.blank_validator]),
        ),
    ]
